/*
 * #%L
 * wcm.io
 * %%
 * Copyright (C) 2023 wcm.io
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package io.wcm.siteapi.genericedit.builder.impl.inspector;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.commons.lang3.Strings;
import org.apache.sling.commons.mime.MimeTypeService;
import org.apache.sling.xss.XSSAPI;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Reference;

import io.wcm.siteapi.genericedit.builder.ValueInspectorService;
import io.wcm.siteapi.genericedit.component.value.MediaValue;

/**
 * Detects Core Components image references.
 */
@Component(service = ValueInspectorService.class)
public class CoreComponentMediaValueInspectorService extends ValueInspectorService<MediaValue> {

  @Reference
  private XSSAPI xssApi;
  @Reference
  private MimeTypeService mimeTypeService;

  /**
   * Pattern to detect image links generated by core components image component.
   */
  private static final Pattern COREIMG_PATTERN = Pattern.compile("^/content/.+/.*\\.coreimg(\\..+)?(\\.[^\\.]+)$");

  @Override
  protected @Nullable MediaValue inspectValue(@NotNull String key, @Nullable Object rawValue,
      @NotNull Object instance) {
    if (rawValue instanceof String) {
      return detectImage((String)rawValue);
    }
    return null;
  }

  private MediaValue detectImage(@NotNull String value) {
    Matcher matcher = COREIMG_PATTERN.matcher(value);
    if (matcher.matches() && isImageMimeType(matcher.group(2))) {
      return new CoreComponentMediaValueImpl(value, xssApi);
    }
    return null;
  }

  private boolean isImageMimeType(@NotNull String extension) {
    String mimeType = mimeTypeService.getMimeType(extension);
    return Strings.CS.startsWith(mimeType, "image/");
  }

}
